# -  /SuhailTechInfo/

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/THUNDERluzer/Hashan /root/THUNDERluze
WORKDIR /root/Suhail/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /SuhailTechInfo/
