# -  /SuhailTechInfo/

FROM quay.io/repository/thunderluzer/thunderluzer
RUN git clone https://github.com/SuhailTechInfo/Suhail-Md /root/thunderluzer
WORKDIR /root/thunderluzer/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /SuhailTechInfo/
