# -  /SuhailTechInfo/

FROM quay.io/thunderluzer/thunderluzer
RUN git clone https://github.com/THUNDERluzer/thunderluzer/root/thunderluzer
WORKDIR /root/thunderluzer/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /SuhailTechInfo/
